blank_issues_enabled: true
contact_links:
  - name: Questions & ideas (Discussions)
    url: https://github.com/gibsonchu/parking-reimagined/discussions
    about: For open-ended questions, ideas, and show-and-tell. Not sure where something goes? Start here.
